/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reproductormultimedia;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.concurrent.TimeUnit;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author tarde
 */
public class ReproductorMultimedia extends javax.swing.JFrame {

    private ImageIcon iIconPausar = new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/2.png");
    private ImageIcon iIconReproducir = new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/1.png");

    private boolean aparecer = true;
    private boolean desplegadoVolumen = true;
    private boolean reproduciendo = true;
    Color a = new Color(0, 102, 51);
    private boolean minimizado = false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReproductorMultimedia.class.getName());

    /**
     * Creates new form ReproductorMultimedia
     */
    public ReproductorMultimedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBotonera = new javax.swing.JPanel();
        jButtonTurnoff = new javax.swing.JButton();
        jButtonVolume = new javax.swing.JButton();
        jSVolumen = new javax.swing.JSlider();
        jButtonStop = new javax.swing.JButton();
        jButtonForward = new javax.swing.JButton();
        jButtonRewind = new javax.swing.JButton();
        jButtonSkip = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();
        jButtonPlayPause = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMaximizar = new javax.swing.JButton();
        jMinimizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelFalso = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIAbrir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBotonera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPBotoneraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPBotoneraMouseExited(evt);
            }
        });
        jPBotonera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTurnoff.setBackground(new java.awt.Color(255, 51, 0));
        jButtonTurnoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/on-off-button.png"))); // NOI18N
        jButtonTurnoff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTurnoffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTurnoffMouseExited(evt);
            }
        });
        jButtonTurnoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTurnoffActionPerformed(evt);
            }
        });
        jPBotonera.add(jButtonTurnoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 52, 50));

        jButtonVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/10.png"))); // NOI18N
        jButtonVolume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVolumeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVolumeMouseExited(evt);
            }
        });
        jButtonVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolumeActionPerformed(evt);
            }
        });
        jPBotonera.add(jButtonVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 52, 50));

        jSVolumen.setVisible(false);
        jSVolumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSVolumenMousePressed(evt);
            }
        });
        jPBotonera.add(jSVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 130, -1));

        jButtonStop.setBackground(new java.awt.Color(204, 204, 0));
        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/7.png"))); // NOI18N
        jButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonStopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonStopMouseExited(evt);
            }
        });
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });
        jPBotonera.add(jButtonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 52, 50));

        jButtonForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/6.png"))); // NOI18N
        jButtonForward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonForwardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonForwardMouseExited(evt);
            }
        });
        jButtonForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForwardActionPerformed(evt);
            }
        });
        jPBotonera.add(jButtonForward, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 52, 50));

        jButtonRewind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/5.png"))); // NOI18N
        jButtonRewind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRewindMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRewindMouseExited(evt);
            }
        });
        jButtonRewind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRewindActionPerformed(evt);
            }
        });
        jPBotonera.add(jButtonRewind, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 52, 50));

        jButtonSkip.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSkip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/3.png"))); // NOI18N
        jButtonSkip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSkipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSkipMouseExited(evt);
            }
        });
        jPBotonera.add(jButtonSkip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 52, 50));

        jButtonRestart.setBackground(new java.awt.Color(0, 153, 153));
        jButtonRestart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/4.png"))); // NOI18N
        jButtonRestart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRestartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRestartMouseExited(evt);
            }
        });
        jPBotonera.add(jButtonRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 52, 50));

        jButtonPlayPause.setBackground(new java.awt.Color(0, 102, 51));
        jButtonPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/1.png"))); // NOI18N
        jButtonPlayPause.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonPlayPauseMouseMoved(evt);
            }
        });
        jButtonPlayPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPlayPauseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPlayPauseMouseExited(evt);
            }
        });
        jButtonPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayPauseActionPerformed(evt);
            }
        });
        jPBotonera.add(jButtonPlayPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 52, 50));

        jProgressBar1.setValue(50);
        jPBotonera.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 27, 240, 20));

        jMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/13.png"))); // NOI18N
        jMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaximizarActionPerformed(evt);
            }
        });
        jPBotonera.add(jMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 52, 50));

        jMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reproductormultimedia/BulkResizePhotos/14.png"))); // NOI18N
        jMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinimizarActionPerformed(evt);
            }
        });
        jPBotonera.add(jMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 52, 50));

        getContentPane().add(jPBotonera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 1230, 80));
        jPBotonera.setVisible(false);

        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));
        jLabel1.setIcon(new ImageIcon("./maxresdefault.jpg"));

        jPanelFalso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFalsoMouseEntered(evt);
            }
        });
        getContentPane().add(jPanelFalso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1280, 140));

        jMenu1.setText("Archivo");

        jMIAbrir.setText("Abrir archivo");
        jMIAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMIAbrir);
        jMIAbrir.getAccessibleContext().setAccessibleName("jMIAbrir");

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAbrirActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.showOpenDialog(this);
        File fichero = selector.getSelectedFile();


    }//GEN-LAST:event_jMIAbrirActionPerformed

    private void jPanelFalsoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFalsoMouseEntered
        this.jPBotonera.setVisible(true);
    }//GEN-LAST:event_jPanelFalsoMouseEntered

    private void jPBotoneraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBotoneraMouseExited

    }//GEN-LAST:event_jPBotoneraMouseExited

    private void jPBotoneraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBotoneraMouseEntered

    }//GEN-LAST:event_jPBotoneraMouseEntered

    private void jMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinimizarActionPerformed

    }//GEN-LAST:event_jMinimizarActionPerformed

    private void jMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaximizarActionPerformed

    }//GEN-LAST:event_jMaximizarActionPerformed

    private void jButtonPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayPauseActionPerformed
        if (reproduciendo) {
            this.jButtonPlayPause.setIcon(iIconPausar);
            this.jButtonPlayPause.setBackground(Color.red);
            reproduciendo = false;

        } else {
            this.jButtonPlayPause.setIcon(iIconReproducir);
            this.jButtonPlayPause.setBackground(new Color(0, 102, 51));
            reproduciendo = true;
        }
    }//GEN-LAST:event_jButtonPlayPauseActionPerformed

    private void jButtonPlayPauseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayPauseMouseExited

    }//GEN-LAST:event_jButtonPlayPauseMouseExited

    private void jButtonPlayPauseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayPauseMouseEntered

    }//GEN-LAST:event_jButtonPlayPauseMouseEntered

    private void jButtonPlayPauseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayPauseMouseMoved

    }//GEN-LAST:event_jButtonPlayPauseMouseMoved

    private void jButtonRestartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRestartMouseExited
        jButtonRestart.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos/4.png"));
    }//GEN-LAST:event_jButtonRestartMouseExited

    private void jButtonRestartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRestartMouseEntered
        jButtonRestart.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/4.png"));
    }//GEN-LAST:event_jButtonRestartMouseEntered

    private void jButtonSkipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSkipMouseExited
        jButtonSkip.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos/3.png"));
    }//GEN-LAST:event_jButtonSkipMouseExited

    private void jButtonSkipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSkipMouseEntered
        jButtonSkip.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/3.png"));
    }//GEN-LAST:event_jButtonSkipMouseEntered

    private void jButtonRewindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRewindActionPerformed
        if (this.jProgressBar1.getValue() >= 5) {
            this.jProgressBar1.setValue(this.jProgressBar1.getValue() - 5);
        }
    }//GEN-LAST:event_jButtonRewindActionPerformed

    private void jButtonRewindMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRewindMouseExited
        jButtonRewind.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos/5.png"));
    }//GEN-LAST:event_jButtonRewindMouseExited

    private void jButtonRewindMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRewindMouseEntered
        jButtonRewind.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/5.png"));
    }//GEN-LAST:event_jButtonRewindMouseEntered

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonStopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseExited
        jButtonStop.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos/7.png"));
    }//GEN-LAST:event_jButtonStopMouseExited

    private void jButtonStopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseEntered
        jButtonStop.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/7.png"));
    }//GEN-LAST:event_jButtonStopMouseEntered

    private void jSVolumenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSVolumenMousePressed
        int volumen = jSVolumen.getValue();
    }//GEN-LAST:event_jSVolumenMousePressed

    private void jButtonVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolumeActionPerformed
        if (desplegadoVolumen) {
            jSVolumen.setVisible(true);
            desplegadoVolumen = false;
        } else {
            jSVolumen.setVisible(false);
            desplegadoVolumen = true;
        }
    }//GEN-LAST:event_jButtonVolumeActionPerformed

    private void jButtonVolumeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolumeMouseExited
        jButtonVolume.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos/10.png"));
    }//GEN-LAST:event_jButtonVolumeMouseExited

    private void jButtonVolumeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolumeMouseEntered
        jButtonVolume.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/10.png"));
    }//GEN-LAST:event_jButtonVolumeMouseEntered

    private void jButtonTurnoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTurnoffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTurnoffActionPerformed

    private void jButtonTurnoffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTurnoffMouseExited
        jButtonTurnoff.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos/on-off-button.png"));
    }//GEN-LAST:event_jButtonTurnoffMouseExited

    private void jButtonTurnoffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTurnoffMouseEntered
        jButtonTurnoff.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/on-off-button.png"));
    }//GEN-LAST:event_jButtonTurnoffMouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jButtonForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForwardActionPerformed
        if (this.jProgressBar1.getMaximum() > this.jProgressBar1.getValue() - 5) {
            this.jProgressBar1.setValue(this.jProgressBar1.getValue() + 5);
        }
    }//GEN-LAST:event_jButtonForwardActionPerformed

    private void jButtonForwardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonForwardMouseExited
        jButtonForward.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos/6.png"));
    }//GEN-LAST:event_jButtonForwardMouseExited

    private void jButtonForwardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonForwardMouseEntered
        jButtonForward.setIcon(new ImageIcon("./src/reproductormultimedia/BulkResizePhotos20/6.png"));
    }//GEN-LAST:event_jButtonForwardMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReproductorMultimedia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForward;
    private javax.swing.JButton jButtonPlayPause;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JButton jButtonRewind;
    private javax.swing.JButton jButtonSkip;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtonTurnoff;
    private javax.swing.JButton jButtonVolume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMIAbrir;
    private javax.swing.JButton jMaximizar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jMinimizar;
    private javax.swing.JPanel jPBotonera;
    private javax.swing.JPanel jPanelFalso;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSlider jSVolumen;
    // End of variables declaration//GEN-END:variables
}
